spring:
  application:
    name: order-service
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BROKER}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-service-id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "br.com.order.order.dto.OrderDto"
      auto-offset-reset: earliest

  data:
    mongodb:
      uri: ${MONGO_URI}

kafka:
  topic:
    name:
      order-processing: order-processing
      order-processed: order-processed
      retry-processing: retry-processing
  retry:
    max-attempt: 5